### ISSUE TITLE
API URL Changed causing Bot not to work anymore

### ISSUE THREAD

**Issue by 8666** [MatejMecka/AirPollutionNotifier#3] opened 2018-05-25 17:16 UTC
http://gorjan.rocks/clients/airquality/returnNewDataWeb.php?lastX=10&type=AQI&location=

Is not available. Alternative link?

**Comment by MatejMecka** [comment] 2018-05-27 14:00
Hey there! Sorry for the late Response. Yep that URL doesn't exist anymore. I can probably guess due to the expansion of the App to Europe too.

**Comment by MatejMecka** [comment] 2018-05-27 14:05
There is another endpoint to Measure pollution but the issue is the AQI has to be calculated by hand: https://mojvozduh.eu/data/api/v3/mk/latestData.css

*ignore the .css it's a JSON API

AQI is measured by getting from each value the maximum it can and the current pollution level.

If 180µg/m3 is maximum for PM10 and we have 126µg/m3 that's 70%. We repeat it for Each one and then pick the largest one to represent.

**Comment by 8666** [comment] 2018-05-27 20:59
Ok, thanks, that should not be a problem.

What is the optimal interval to redownload the data? Better would be if you can publish the data to MQTT broker so we can get instant updates and not query the API.

**Comment by 8666** [comment] 2018-05-27 21:00
I am using this for personal needs only and need data for one station only.

**Comment by MatejMecka** [comment] 2018-05-28 15:45
The optimal Interval should be an 1 since that's when the sensors update the Data.

The data is Scraped so It will be hard to link with an MQTT Broker. 

also the reason the API was changed that the previous Urls weren't hosted under a CDN. The current URL is. The Individual URL's i could guess were removed so there is only one Request made to the server instead of Multiple. So I guess you'll have to Parse all the stations and select the one based on your needs

**Comment by MatejMecka** [comment] 2018-05-28 15:45
#1 Will be closed as it's no longer an enhacment but a Requirement

**Comment by MatejMecka** [comment] 2018-07-23 12:31
Fixed with commit 82d29e7! 

Thanks for reporting the issue @8666 and bringing my attention to this

**Closed as completed by MatejMecka** 2018-07-23 12:31 UTC
Labels: bug, Priority 1
